name: Firebase Functions CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Authenticate with Firebase
        run: firebase login:ci --no-localhost --token ${{ secrets.1//05DPaEiom70l1CgYIARAAGAUSNwF-L9IrWyoGgorPa66y9PyS5gl6LXGKtfVkGQDZpt1jwaU0vKb9TNVbocV0Ojv4U0GgA42hboE
 }}
      - name: Install Dependencies
        run: npm install
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
